language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - "python setup.py install"
  - "pip install -r test_requirements.txt"
# command to run tests
script: nosetests --with-coverage --cover-package fulcrum
after_script:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
